
networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3606:3306"
    networks:
      - algafood-network
  
  algafood-redis:
    image: redis:7.0-alpine
    networks:
      - algafood-network
      
  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      EMAIL: abner.pelisser@gmail.com
      SENHA_EMAIL: senha_email_aqui
      EMAIL_REMETENTE: abner.pelisser@gmail.com
      S3_ACCESS_KEY: s3_access_key_aqui
      S3_SECRET_ACCESS_KEY: s3_secret_access_key_aqui
      LOGGLY_TOKEN: loggly_token_aqui
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql
      
  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api